// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: GRPCclient/crud.proto

package pbf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEmployeeByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByIDRequest) Reset() {
	*x = GetEmployeeByIDRequest{}
	mi := &file_GRPC_client_crud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByIDRequest) ProtoMessage() {}

func (x *GetEmployeeByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_client_crud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByIDRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeByIDRequest) Descriptor() ([]byte, []int) {
	return file_GRPC_client_crud_proto_rawDescGZIP(), []int{0}
}

func (x *GetEmployeeByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEmployeesRequest) Reset() {
	*x = GetAllEmployeesRequest{}
	mi := &file_GRPC_client_crud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmployeesRequest) ProtoMessage() {}

func (x *GetAllEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_client_crud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmployeesRequest.ProtoReflect.Descriptor instead.
func (*GetAllEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_GRPC_client_crud_proto_rawDescGZIP(), []int{1}
}

type CreateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeRequest) Reset() {
	*x = CreateEmployeeRequest{}
	mi := &file_GRPC_client_crud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeRequest) ProtoMessage() {}

func (x *CreateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_client_crud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_GRPC_client_crud_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEmployeeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEmployeeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateEmployeeRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type UpdateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeRequest) Reset() {
	*x = UpdateEmployeeRequest{}
	mi := &file_GRPC_client_crud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeRequest) ProtoMessage() {}

func (x *UpdateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_client_crud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_GRPC_client_crud_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEmployeeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEmployeeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type DeleteEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmployeeRequest) Reset() {
	*x = DeleteEmployeeRequest{}
	mi := &file_GRPC_client_crud_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeRequest) ProtoMessage() {}

func (x *DeleteEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_client_crud_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_GRPC_client_crud_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteEmployeeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_GRPC_client_crud_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_client_crud_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_GRPC_client_crud_proto_rawDescGZIP(), []int{5}
}

func (x *Employee) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Employee) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Employee) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type EmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeResponse) Reset() {
	*x = EmployeeResponse{}
	mi := &file_GRPC_client_crud_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeResponse) ProtoMessage() {}

func (x *EmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_client_crud_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeResponse.ProtoReflect.Descriptor instead.
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return file_GRPC_client_crud_proto_rawDescGZIP(), []int{6}
}

func (x *EmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type EmployeesListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeesListResponse) Reset() {
	*x = EmployeesListResponse{}
	mi := &file_GRPC_client_crud_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeesListResponse) ProtoMessage() {}

func (x *EmployeesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GRPC_client_crud_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeesListResponse.ProtoReflect.Descriptor instead.
func (*EmployeesListResponse) Descriptor() ([]byte, []int) {
	return file_GRPC_client_crud_proto_rawDescGZIP(), []int{7}
}

func (x *EmployeesListResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

var File_GRPC_client_crud_proto protoreflect.FileDescriptor

const file_GRPC_client_crud_proto_rawDesc = "" +
	"\n" +
	"\x16GRPC-client/crud.proto\x12\x04crud\"(\n" +
	"\x16GetEmployeeByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x18\n" +
	"\x16GetAllEmployeesRequest\"S\n" +
	"\x15CreateEmployeeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\"c\n" +
	"\x15UpdateEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\"'\n" +
	"\x15DeleteEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"V\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\">\n" +
	"\x10EmployeeResponse\x12*\n" +
	"\bemployee\x18\x01 \x01(\v2\x0e.crud.EmployeeR\bemployee\"E\n" +
	"\x15EmployeesListResponse\x12,\n" +
	"\temployees\x18\x01 \x03(\v2\x0e.crud.EmployeeR\temployees2\xfd\x02\n" +
	"\x0fEmployeeService\x12G\n" +
	"\x0fGetEmployeeByID\x12\x1c.crud.GetEmployeeByIDRequest\x1a\x16.crud.EmployeeResponse\x12L\n" +
	"\x0fGetAllEmployees\x12\x1c.crud.GetAllEmployeesRequest\x1a\x1b.crud.EmployeesListResponse\x12E\n" +
	"\x0eCreateEmployee\x12\x1b.crud.CreateEmployeeRequest\x1a\x16.crud.EmployeeResponse\x12E\n" +
	"\x0eUpdateEmployee\x12\x1b.crud.UpdateEmployeeRequest\x1a\x16.crud.EmployeeResponse\x12E\n" +
	"\x0eDeleteEmployee\x12\x1b.crud.DeleteEmployeeRequest\x1a\x16.crud.EmployeeResponseB\x1aZ\x18awesomeProject/pb-serverb\x06proto3"

var (
	file_GRPC_client_crud_proto_rawDescOnce sync.Once
	file_GRPC_client_crud_proto_rawDescData []byte
)

func file_GRPC_client_crud_proto_rawDescGZIP() []byte {
	file_GRPC_client_crud_proto_rawDescOnce.Do(func() {
		file_GRPC_client_crud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GRPC_client_crud_proto_rawDesc), len(file_GRPC_client_crud_proto_rawDesc)))
	})
	return file_GRPC_client_crud_proto_rawDescData
}

var file_GRPC_client_crud_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_GRPC_client_crud_proto_goTypes = []any{
	(*GetEmployeeByIDRequest)(nil), // 0: crud.GetEmployeeByIDRequest
	(*GetAllEmployeesRequest)(nil), // 1: crud.GetAllEmployeesRequest
	(*CreateEmployeeRequest)(nil),  // 2: crud.CreateEmployeeRequest
	(*UpdateEmployeeRequest)(nil),  // 3: crud.UpdateEmployeeRequest
	(*DeleteEmployeeRequest)(nil),  // 4: crud.DeleteEmployeeRequest
	(*Employee)(nil),               // 5: crud.Employee
	(*EmployeeResponse)(nil),       // 6: crud.EmployeeResponse
	(*EmployeesListResponse)(nil),  // 7: crud.EmployeesListResponse
}
var file_GRPC_client_crud_proto_depIdxs = []int32{
	5, // 0: crud.EmployeeResponse.employee:type_name -> crud.Employee
	5, // 1: crud.EmployeesListResponse.employees:type_name -> crud.Employee
	0, // 2: crud.EmployeeService.GetEmployeeByID:input_type -> crud.GetEmployeeByIDRequest
	1, // 3: crud.EmployeeService.GetAllEmployees:input_type -> crud.GetAllEmployeesRequest
	2, // 4: crud.EmployeeService.CreateEmployee:input_type -> crud.CreateEmployeeRequest
	3, // 5: crud.EmployeeService.UpdateEmployee:input_type -> crud.UpdateEmployeeRequest
	4, // 6: crud.EmployeeService.DeleteEmployee:input_type -> crud.DeleteEmployeeRequest
	6, // 7: crud.EmployeeService.GetEmployeeByID:output_type -> crud.EmployeeResponse
	7, // 8: crud.EmployeeService.GetAllEmployees:output_type -> crud.EmployeesListResponse
	6, // 9: crud.EmployeeService.CreateEmployee:output_type -> crud.EmployeeResponse
	6, // 10: crud.EmployeeService.UpdateEmployee:output_type -> crud.EmployeeResponse
	6, // 11: crud.EmployeeService.DeleteEmployee:output_type -> crud.EmployeeResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GRPC_client_crud_proto_init() }
func file_GRPC_client_crud_proto_init() {
	if File_GRPC_client_crud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GRPC_client_crud_proto_rawDesc), len(file_GRPC_client_crud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_GRPC_client_crud_proto_goTypes,
		DependencyIndexes: file_GRPC_client_crud_proto_depIdxs,
		MessageInfos:      file_GRPC_client_crud_proto_msgTypes,
	}.Build()
	File_GRPC_client_crud_proto = out.File
	file_GRPC_client_crud_proto_goTypes = nil
	file_GRPC_client_crud_proto_depIdxs = nil
}
